#Aleksandrs Lukjanovs - M00674847 - 2020-21 CST2555 Operating Systems and Computer Networks
#CompLab1/01 Tutor Name: Ahmed Eissa
#myshell , functions, makefile
myshell: myshell.cpp functions.cpp
	g++ -std=c++17 -Wall -Werror -Wextra -o myshell myshell.cpp -lstdc++fs
	
clean:
	rm myshell